[package]
name = "clear"
version = "0.1.0"
authors = ["Mathieu D. <mathieu.delacroix.fr@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0" # In order to build our binary as a cli
regex = "1.3.1" # Because regexp
