[app]
name    = "Demo"
version = 0.1
secret  = "secretkeyrandomized"
authors = ["Mathieu D. <dlacreme@gmail.com>"]
target    = "./demo/src/clear_demo.clr"

[hosting]
port  = 4242

[database]
addon     = "postgresql"
host      = "localhost"
port      = 5432
database  = "clear_demo"
user      = "clear"
password  = "clear"

[interpreter]
language  = "python"
bin       = "/usr/bin/python3.8"
