// PEST feature to automaticaly skip whitespaces
WHITESPACE = _{ " " }

comment = { "#" ~ (ASCII_ALPHA | ASCII_DIGIT | ".")* }
// Types
quote = { "\""|"'" }
string = { quote ~ (ASCII_ALPHA | ASCII_DIGIT | " ")+ ~ quote }
number = { (ASCII_DIGIT | ".")+ }

// // Functions
args = { (string | number)* }
func = { ASCII_ALPHA ~ "(" ~ (string|number)* ~ ")" }

// Source File

my_newline = { (comment ~ NEWLINE | NEWLINE) }

file = {
    SOI ~
    ((comment|func)? ~ my_newline)* ~
    EOI
}
